# SPDX-License-Identifier: MIT
# Generated from marvin/voice/v1/voice.proto by host/scripts/gen_voice_contract.py: do not edit.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import voice_pb2 as marvin_dot_voice_dot_v1_dot_voice__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in marvin/voice/v1/voice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/marvin.voice.v1.Voice/Session',
                request_serializer=marvin_dot_voice_dot_v1_dot_voice__pb2.CoreToVoice.SerializeToString,
                response_deserializer=marvin_dot_voice_dot_v1_dot_voice__pb2.VoiceToCore.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_unary(
                '/marvin.voice.v1.Voice/Transcribe',
                request_serializer=marvin_dot_voice_dot_v1_dot_voice__pb2.AudioClip.SerializeToString,
                response_deserializer=marvin_dot_voice_dot_v1_dot_voice__pb2.Transcript.FromString,
                _registered_method=True)
        self.Options = channel.unary_unary(
                '/marvin.voice.v1.Voice/Options',
                request_serializer=marvin_dot_voice_dot_v1_dot_voice__pb2.OptionsRequest.SerializeToString,
                response_deserializer=marvin_dot_voice_dot_v1_dot_voice__pb2.VoiceOptions.FromString,
                _registered_method=True)


class VoiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Session(self, request_iterator, context):
        """The live session: audio and commands in, what the voice hears and does out.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Batch recognition, for recordings: not the live loop.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Options(self, request, context):
        """What the settings can offer: backends, models, voices (the app's voice settings).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=marvin_dot_voice_dot_v1_dot_voice__pb2.CoreToVoice.FromString,
                    response_serializer=marvin_dot_voice_dot_v1_dot_voice__pb2.VoiceToCore.SerializeToString,
            ),
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=marvin_dot_voice_dot_v1_dot_voice__pb2.AudioClip.FromString,
                    response_serializer=marvin_dot_voice_dot_v1_dot_voice__pb2.Transcript.SerializeToString,
            ),
            'Options': grpc.unary_unary_rpc_method_handler(
                    servicer.Options,
                    request_deserializer=marvin_dot_voice_dot_v1_dot_voice__pb2.OptionsRequest.FromString,
                    response_serializer=marvin_dot_voice_dot_v1_dot_voice__pb2.VoiceOptions.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marvin.voice.v1.Voice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marvin.voice.v1.Voice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Voice:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/marvin.voice.v1.Voice/Session',
            marvin_dot_voice_dot_v1_dot_voice__pb2.CoreToVoice.SerializeToString,
            marvin_dot_voice_dot_v1_dot_voice__pb2.VoiceToCore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marvin.voice.v1.Voice/Transcribe',
            marvin_dot_voice_dot_v1_dot_voice__pb2.AudioClip.SerializeToString,
            marvin_dot_voice_dot_v1_dot_voice__pb2.Transcript.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Options(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marvin.voice.v1.Voice/Options',
            marvin_dot_voice_dot_v1_dot_voice__pb2.OptionsRequest.SerializeToString,
            marvin_dot_voice_dot_v1_dot_voice__pb2.VoiceOptions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
