"""The voice sidecar: Marvin's real-time audio loop as a separate process, for the Java core.

    python -m marvin_host.sidecar.voice --port 0          # prints READY port=<port>

It owns everything timing-critical about speech (docs/design.md, section 4.3): the microphone
(the computer's, or the robot's as the core relays it), the echo gate, VAD, the wake word and
listening windows, speculative speech recognition and its filters, chunking text for speech,
synthesis and playback (the computer's speakers, or the robot's, paced for it), barge-in, and the
live signals of the app. It does not decide what to answer: a question goes to the core
(`Heard`), and the core streams the answer's text back (`ReplyStart`, `TextPiece`, `Filler`,
`ReplyEnd`). The contract is host-java/marvin-contracts/src/main/proto/marvin/voice/v1/voice.proto.

The audio machine is the same code as the in-process assistant of `marvin-host run` and
`marvin-host talk` (voice/engine.py): only the source of the answers differs.

Modules: server (gRPC services), session (one core's session, the engine's life), engine
(`SidecarVoice`), relay (the robot's audio through the core), fake (test mode), cli, contract
(generated by host/scripts/gen_voice_contract.py).

Install: pip install -e ".[sidecar,voice]" in the host folder.

SPDX-License-Identifier: MIT
"""
