-- SPDX-License-Identifier: MIT
-- The presence history (the Python host's store.py): brain events and the host's own markers, stamped
-- with the host's wall clock (Unix seconds, as the app uses them), and one sample per minute.
-- data is json, not jsonb: the keys keep their order, as the app shows them.
CREATE TABLE event (
  id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts     double precision NOT NULL,
  kind   text NOT NULL,
  detail text NOT NULL DEFAULT '',
  data   json NOT NULL DEFAULT '{}',
  t_us   bigint                                   -- the robot's clock, for reference
);
CREATE INDEX event_ts ON event (ts);

CREATE TABLE sample (
  ts      double precision PRIMARY KEY,           -- the minute's start
  present double precision NOT NULL,              -- fraction of the minute someone was there
  seated  double precision NOT NULL,
  breath  double precision,                       -- per minute, NULL when not reliable
  heart   double precision
);
